#!/bin/sh

# Spawn zathura window as a new tab in the specific tabbed window. Modified
# from https://github.com/mtikekar/zathura-tabbed/blob/master/zathura-tabbed

xidfile="/run/user/"$(id -u)"/zathura-tabbed.xid"
wmclass="zathura-tabbed"

# check if a tabbed window is open
if [ -r "$xidfile" ] && xid=$(cat "$xidfile") && xprop -id "$xid" WM_CLASS 2> /dev/null | grep -q "$wmclass";
then
    seturgent "$xid"
else
    xid=$(tabbed -scdn "$wmclass" -p -1 -r 2 zathura -e "" 2> /dev/null)
    echo "$xid" > "$xidfile"
fi

zathura -e "$xid" "$@" &> /dev/null &
